version: 2
project_name: ganache-admin
before:
  hooks:
    - go mod tidy

builds:
  - id: ui
    main: ./cmd/ganache-admin-ui
    binary: ganache-admin-ui
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: cli
    main: ./cmd/ganache-admin-cli
    binary: ganache-admin-cli
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: ui
    builds:
      - ui
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}-ui_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
    wrap_in_directory: true

  - id: cli
    builds:
      - cli
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}-cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
    wrap_in_directory: true

checksum:
  name_template: "checksums.txt"

sboms:
  - id: archive
    artifacts: archive

changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^chore:'
